/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/utils/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        barlow: ["Barlow", "sans-serif"], // Main font
        roboto: ["Roboto", "sans-serif"], // Secondary font
      },
      fontSize: {
        displayLarge: [
          "57px",
          { lineHeight: "64px", letterSpacing: "-0.25px" },
        ],
        displayMedium: ["45px", { lineHeight: "52px", letterSpacing: "0px" }],
        displaySmall: ["36px", { lineHeight: "44px", letterSpacing: "0px" }],
        headlineLarge: ["32px", { lineHeight: "40px", letterSpacing: "0px" }],
        headlineMedium: ["28px", { lineHeight: "36px", letterSpacing: "0px" }],
        headlineSmall: ["24px", { lineHeight: "32px", letterSpacing: "0px" }],
        titleLarge: ["22px", { lineHeight: "28px", letterSpacing: "0px" }],
        titleMedium: ["16px", { lineHeight: "24px", letterSpacing: "0.15px" }],
        titleSmall: ["14px", { lineHeight: "20px", letterSpacing: "0.1px" }],
        labelXLarge: ["18px", { lineHeight: "20px", letterSpacing: "0.1px" }],
        labelLarge: ["14px", { lineHeight: "20px", letterSpacing: "0.1px" }],
        labelMedium: ["12px", { lineHeight: "16px", letterSpacing: "0.5px" }],
        labelSmall: ["11px", { lineHeight: "16px", letterSpacing: "0.5px" }],
        bodyLarge: ["16px", { lineHeight: "24px", letterSpacing: "0.5px" }],
        bodyMedium: ["14px", { lineHeight: "20px", letterSpacing: "0.25px" }],
        bodySmall: ["12px", { lineHeight: "16px", letterSpacing: "0.4px" }],
      },
      fontWeight: {
        regular: "400",
        medium: "500",
        semibold: "600",
      },
      letterSpacing: {
        tightest: "-.075em",
        tighter: "-.05em",
        tight: "-.025em",
        normal: "0",
        wide: ".025em",
        wider: ".05em",
        widest: ".1em",
        custom1: "0.15em",
        custom2: "0.1em",
      },
      colors: {
        primary: {
          light: "#FDE8E9",
          hover: "#FCDDDE",
          active: "#F9B9BB",
          normal: "#ED1C24",
          hover_normal: "#D51920",
          active_normal: "#BE161D",
          dark: "#B2151B",
          hover_dark: "#8E1116",
          active_dark: "#6B0D10",
          darker: "#530A0D",
          disabled: "#E5E7EB",
          disabled_dark: "#6B7280",
        },
        secondary: {
          light: "#E8ECE9",
          hover: "#DCE2DF",
          active: "#B7C3BC",
          normal: "#183F27",
          hover_normal: "#163923",
          active_normal: "#133211",
          dark: "#12281D",
          hover_dark: "#0E2617",
          active_dark: "#0B1C12",
          darker: "#08160E",
        },
        tertiary1: {
          light: "#EAEAEA",
          hover: "#E0E0E0",
          active: "#BFBEBE",
          normal: "#2F2E2E",
          hover_normal: "#2A2929",
          active_normal: "#262525",
          dark: "#232323",
          hover_dark: "#1C1C1C",
          active_dark: "#151515",
          darker: "#101010",
        },
        tertiary2: {
          light: "#FEFEFE",
          hover: "#FDFDFD",
          active: "#FBFBFB",
          normal: "#F1F1F1",
          hover_normal: "#D9D9D9",
          active_normal: "#C1C1C1",
          dark: "#B5B5B5",
          hover_dark: "#919191",
          active_dark: "#6C6C6C",
          darker: "#545454",
        },
        calendar: {
          full: "#FF3B30",
          full_light: "#FEEBEB",
          limited: "#FF9500",
          limited_light: "#FF95004D",
          open: "#34C759",
          open_dark: "#1A8245",
          open_light: "#DAF8E6",
          today_ring: "#F37277",
        },
        others: {
          confirm: "#34C759",
          negative: "#FF3B30",
          gray: "#637381",
          bordergray: "#DFE4EA",
          dark: "#111928",
          sliderburgundy: "#2E0607",
          sliderbackground: "#d1d5db",
        },
      },
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
        "3xl": "1780px",
      },
      backgroundImage: {
        "dots-lg": "radial-gradient(circle, #FCDDDD 4px, transparent 1px)",
        "dots-sm": "radial-gradient(circle, #FCDDDD 3px, transparent 1px)",
      },
      backgroundSize: {
        "dots-size-lg": "35px 35px",
        "dots-size-sm": "25px 25px",
      },
    },
  },
  darkMode: "class", // Enable dark mode using a class
  plugins: [],
};
