export const getWineBySlug = (slug, wines) => {
  return wines.find((wine) => wine.slug === slug);
};
// const wines = [
//   {
//     title: "Muga Reserva",
//     slug: "muga-reserva",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non erat quam. Vestibulum aliquam nibh dui, et aliquet nibh euismod quis.",
//     price: 24.5,
//     casePrice: 123,
//     rating: 5.0,
//     nrOfRatings: 10,
//     volume: 1.0,
//     quantity: 5,
//     country: "Argentina",
//     region: "Mendoza",
//     vineyard: "Alamos",
//     wineColor: "Red",
//     grape: "Malbec",
//     imageUrl: "/images/exampleImageWine.png",
//     isNew: true,
//     url: "/wine-details/muga-reserva",
//   },
//   {
//     title: "Barolo Terlo",
//     slug: "barolo-terlo",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non erat quam. Vestibulum aliquam nibh dui, et aliquet nibh euismod quis.",
//     price: 24.5,
//     casePrice: 123,
//     rating: 4.0,
//     nrOfRatings: 10,
//     volume: 0.7,
//     quantity: 10,
//     country: "Argentina",
//     region: "Mendoza",
//     vineyard: "Alamos",
//     wineColor: "Red",
//     grape: "Malbec",
//     imageUrl: "/images/exampleImageWine.png",
//     isNew: true,
//     url: "/wine-details/barolo-terlo",
//   },
//   {
//     title: "Pinot Noir",
//     slug: "pinot-noir",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non erat quam. Vestibulum aliquam nibh dui, et aliquet nibh euismod quis.",
//     price: 24.5,
//     casePrice: 123,
//     rating: 4.5,
//     nrOfRatings: 10,
//     volume: 1.0,
//     quantity: 0,
//     country: "Argentina",
//     region: "Mendoza",
//     vineyard: "Alamos",
//     wineColor: "Red",
//     grape: "Malbec",
//     imageUrl: "/images/exampleImageWine.png",
//     isNew: false,
//     url: "/wine-details/pinot-noir",
//   },
//   {
//     title: "Vega Cicilia",
//     slug: "vega-cicilia",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non erat quam. Vestibulum aliquam nibh dui, et aliquet nibh euismod quis.",
//     price: 24.5,
//     casePrice: 123,
//     rating: 3.5,
//     nrOfRatings: 10,
//     volume: 1.0,
//     quantity: 3,
//     country: "Argentina",
//     region: "Mendoza",
//     vineyard: "Alamos",
//     wineColor: "Red",
//     grape: "Malbec",
//     imageUrl: "/images/exampleImageWine.png",
//     isNew: false,
//     url: "/wine-details/vega-cicilia",
//   },
//   {
//     title: "Saviognese Merlot",
//     slug: "saviognese-merlot",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non erat quam. Vestibulum aliquam nibh dui, et aliquet nibh euismod quis.",
//     price: 24.5,
//     casePrice: 123,
//     rating: 3.0,
//     nrOfRatings: 10,
//     volume: 1.0,
//     quantity: 25,
//     country: "Argentina",
//     region: "Mendoza",
//     vineyard: "Alamos",
//     wineColor: "Red",
//     grape: "Malbec",
//     imageUrl: "/images/exampleImageWine.png",
//     isNew: true,
//     url: "/wine-details/saviognese-merlot",
//   },
//   {
//     title: "Pinot Grigio",
//     slug: "pinot-grigio",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non erat quam. Vestibulum aliquam nibh dui, et aliquet nibh euismod quis.",
//     price: 24.5,
//     casePrice: 123,
//     rating: 5.0,
//     nrOfRatings: 10,
//     volume: 1.0,
//     quantity: 35,
//     country: "Argentina",
//     region: "Mendoza",
//     vineyard: "Alamos",
//     wineColor: "Red",
//     grape: "Malbec",
//     imageUrl: "/images/exampleImageWine.png",
//     isNew: false,
//     url: "/wine-details/pinot-grigio",
//   },
//   {
//     title: "Marques de Murrieta",
//     slug: "marques-de-murrieta",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non erat quam. Vestibulum aliquam nibh dui, et aliquet nibh euismod quis.",
//     price: 24.5,
//     casePrice: 123,
//     rating: 5.0,
//     nrOfRatings: 10,
//     volume: 1.0,
//     quantity: 7,
//     country: "Argentina",
//     region: "Mendoza",
//     vineyard: "Alamos",
//     wineColor: "Red",
//     grape: "Malbec",
//     imageUrl: "/images/exampleImageWine.png",
//     isNew: false,
//     url: "/wine-details/marques-de-murrieta",
//   },
// ];

// // const winesWithStock = wines.map((wine) => ({
// //   ...wine,
// //   inStock: wine.quantity > 0,
// // }));

// // return winesWithStock.find((wine) => wine.slug === slug);
